config/routes.rb
MotivateMe::Application.routes.draw do
  match '/',        to: 'pages#home',     via: 'get'
  match '/about',   to: 'pages#about',    via: 'get'
  match '/help',    to: 'pages#help',     via: 'get'
  match '/contact', to: 'pages#contact',  via: 'get'

  match '/signup',  to: 'users#new',        via: 'get'
  match '/signin',  to: 'sessions#new',     via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'
  
  resources :categories
  resources :users
  resources :sessions, only: [:new, :create, :destroy]

  root 'pages#home'

  

end

app/models/category.rb
class Category < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
	before_save { self.email = email.downcase }
	before_create :create_remember_token
	validates :name, presence: true, length: { maximum: 50 }
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, presence: true, format: { with: VALID_EMAIL_REGEX },  uniqueness: { case_sensitive: false }

	has_secure_password
	validates :password, length: { minimum: 6 }

	def User.new_remember_token
		SecureRandom.urlsafe_base64
	end

	def User.encrypt(token)
		Digest::SHA1.hexdigest(token.to_s)
	end

	private

		def create_remember_token
			self.remember_token = User.encrypt(User.new_remember_token)
		end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render action: 'show', status: :created, location: @category }
      else
        format.html { render action: 'new' }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name, :description)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

  def contact
  	#I18n.locale = :es
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
		
	end

	def create
		user = User.find_by(email: params[:session][:email].downcase)
		if user && user.authenticate(params[:session][:password])
			sign_in user
			redirect_to user
		else
			flash.now[:error] = 'Invalid email/password combination'
			render 'new'
		end
	end

	def destroy
	    sign_out
	    redirect_to root_url
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def new
  	@user = User.new
  end

  def show
  	@user = User.find(params[:id])
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      sign_in @user
    	flash[:success] = t("Welcome to the Sample App!")
      redirect_to @user
    else
      render 'new'
    end
  end

private
	def user_params
		params.require(:user).permit(:name, :email, :password,
		:password_confirmation)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def sign_in(user)
		remember_token = User.new_remember_token
		cookies.permanent[:remember_token] = remember_token
		user.update_attribute(:remember_token, User.encrypt(remember_token))
		self.current_user = user
	end

	def current_user=(user)
		@current_user = user
	end

	def current_user
		remember_token = User.encrypt(cookies[:remember_token])
		@current_user ||= User.find_by(remember_token: remember_token)
	end

	def signed_in?
	    !current_user.nil?
	end

	def sign_out
		self.current_user = nil
		cookies.delete(:remember_token)
	end
end

app/helpers/users_helper.rb
module UsersHelper
	# Returns the Gravatar (http://gravatar.com/) for the given user.
	def gravatar_for(user)
		gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
		gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
		image_tag(gravatar_url, alt: user.name, class: "gravatar")
	end
end

app/views/categories/_form.html.haml
= simple_form_for(@category) do |f|
  = f.error_notification

  .form-inputs
    = f.input :name
    = f.input :description, as: :text

  .form-actions
    = f.button :submit, class:'btn btn-primary' 

app/views/categories/edit.html.haml
%h1 Editing category

= render 'form'

= link_to 'Show', @category
\|
= link_to 'Back', categories_path

app/views/categories/index.html.haml
= content_for :title, "Categories"
%h1 Listing categories

%table.table
  %tr
    %th Name
    %th=t("Description")
    %th
    %th

  - @categories.each do |category|
    %tr
      %td= category.name
      %td= category.description
      %td
        = link_to 'Show', category
        = link_to 'Edit', edit_category_path(category)
        = link_to 'Destroy', category, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Category', new_category_path

app/views/categories/new.html.haml
%h1 New category

= render 'form'

= link_to 'Back', categories_path

app/views/categories/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @category.name

= link_to 'Edit', edit_category_path(@category)
\|
= link_to 'Back', categories_path

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%= link_to image_tag("smile_16.png", :border => 0, class:"img-brand") + "Motivate-me", "/", :class => 'brand' %>
<ul class="nav">
	<li>
		<%= link_to t('Categories'), categories_path %>
	</li>
</ul>
<ul class="nav pull-right">
  <li><%= link_to t("Home"),    root_path %></li>
  <li><%= link_to t("Help"),    help_path %></li>
  <li><%= link_to t("Contact"),    contact_path %></li>
  
  <% if signed_in? %>
  <li><%= link_to "Users", '#' %></li>
  <li id="fat-menu" class="dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
      Account <b class="caret"></b>
    </a>
    <ul class="dropdown-menu">
      <li><%= link_to "Profile", current_user %></li>
      <li><%= link_to "Settings", '#' %></li>
      <li class="divider"></li>
      <li>
        <%= link_to "Sign out", signout_path, method: "delete" %>
      </li>
    </ul>
  </li>
  <% else %>
  <li><%= link_to "Sign in", signin_path %></li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? "Motivame | " + yield(:title) : "Motivame" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Rails Bootstrap" %>">
    <%= stylesheet_link_tag "application", :media => "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header class="navbar navbar-fixed-top">
      <nav class="navbar-inner">
        <div class="container">
          <%= render 'layouts/navigation' %>
        </div>
      </nav>
    </header>
    <main role="main">
      <div class="container">
        <div class="content">
           <div class="row">
            <div class="span12">
              <%= render 'layouts/messages' %>
              <%= yield %>
              <%= debug(params) if Rails.env.development? %>
            </div>
          </div>
          <footer>
          </footer>
        </div>
      </div>
    </main>
  </body>
</html>

app/views/pages/about.html.haml
%h1 About Us
%p Interdum et malesuada fames ac ante ipsum primis in faucibus. Maecenas volutpat facilisis ante non vulputate. Integer ultrices facilisis pulvinar. Vivamus risus velit, placerat at eros sit amet, rhoncus tempus magna.
%p Aliquam in lacinia sapien. Curabitur lectus diam, dictum ac pharetra sit amet, mattis eleifend leo. Ut in tellus eu mauris feugiat ultricies ac in urna. Proin dignissim dolor vel mauris tristique, pellentesque porta magna iaculis. Aenean cursus, erat non tristique elementum, erat odio dignissim ligula, ut imperdiet justo nibh sit amet massa. Mauris ac tempor urna. Vestibulum in turpis enim. Aliquam eleifend ut felis vitae dapibus. Proin pharetra sagittis est et molestie. Suspendisse potenti. Mauris tempus, ante quis scelerisque pulvinar, nunc mauris malesuada diam, non laoreet mauris ligula a ligula.

app/views/pages/contact.html.haml
=provide :title, "Contact" 
%h1 
	=t('Contact')
%p Find me in app/views/pages/about.html.haml

app/views/pages/help.html.haml
%h1 Help
%p Find me in app/views/pages/help.html.haml

app/views/pages/home.html.haml
=provide :title, "Home"
.hero-unit 
	
	-# %h2 Welcome!
	-# %div{:style=>"float:left"}
	.row
		.span5
			= image_tag("ppal_banner.jpg", alt: "banner")
		.span5
			%h1{style:"color:gray"}
				Motivate 
				%span{style:"color:orange"} Me
			%p Interdum et malesuada fames ac ante ipsum primis in faucibus. Maecenas volutpat facilisis ante non vulputate. Integer ultrices facilisis pulvinar.
			%p Vivamus risus velit, placerat at eros sit amet, rhoncus tempus magna. Aliquam in lacinia sapien. Curabitur lectus diam, dictum ac pharetra sit amet, mattis eleifend leo. Ut in tellus eu mauris feugiat ultricies ac in urna.

		= link_to "Sign up now!", signup_path, class: "btn btn-large btn-primary ", style:"float:right"

%p Vivamus risus velit, placerat at eros sit amet, rhoncus tempus magna. Aliquam in lacinia sapien. Curabitur lectus diam, dictum ac pharetra sit amet, mattis eleifend leo. Ut in tellus eu mauris feugiat ultricies ac in urna.
%p Proin dignissim dolor vel mauris tristique, pellentesque porta magna iaculis. Aenean cursus, erat non tristique elementum, erat odio dignissim ligula, ut imperdiet justo nibh sit amet massa. Mauris ac tempor urna. Vestibulum in turpis enim. Aliquam eleifend ut felis vitae dapibus. Proin pharetra sagittis est et molestie.
%p Suspendisse potenti. Mauris tempus, ante quis scelerisque pulvinar, nunc mauris malesuada diam, non laoreet mauris ligula a ligula.

app/views/users/new.html.haml
=provide :title, 'Sign up'

%h1 
	=t("Sign Up")

= simple_form_for(@user) do |f|
	= f.error_notification

	.form-inputs
		= f.input :name
		= f.input :email
		= f.input :password
		= f.input :password_confirmation,label: "Confirmation"

	.form-actions
		-#= f.submit "Create my account", class:'btn btn-primary' 
		= f.button :submit, "Create my Account", class:'btn-primary' 

app/views/users/show.html.haml
=provide :title, @user.name

%h1.center
	= gravatar_for @user
	=@user.name
= @user.name
= @user.email